### ISSUE TITLE
cloudformation deploy CLI exits with return code 255 if stack exists

### ISSUE THREAD

**Issue by jghaines** [awslabs/serverless-application-model#71]
I'm trying to deploy AWS SAM in a CI/CD pipeline. I'm calling the "deploy" command from an ansible shell which then fails if the stack exists

If "aws cloudformation deploy" is run on an existing stack (e.g. re-run) it outputs:

> No changes to deploy. Stack <stack-name> is up to date

And exits with error code 255.

Based on
https://docs.aws.amazon.com/cli/latest/topic/return-codes.html
I'd suggest this is not really a "Command failed" error.

Better would be to return 0, or another value (!=0 and != 255) to indicate no-op.

**Comment by gertjvr** [comment]
Hit the same issue recently, this is really a show stopper regarding using deploy in a CI/CD pipeline as we need to swallow the exception or sniff the message to determine if the exception can be ignored.

**Comment by jghaines** [comment]
I wrote the wrapper `aws-cloudformation.sh` script below as a workaround

    #!/bin/bash
    
    # wrapper around "aws cloudformation" CLI to ignore certain pseudo-errors
    
    # aws cloudformation deploy exits with 255 for "No changes to deploy" see: https://github.com/awslabs/serverless-application-model/issues/71
    # this script exits with 0 for that case
    
    STDERR=$(( aws cloudformation "$@" ) 2>&1)
    ERROR_CODE=$?
    echo ${STDERR} 1>&2
    
    if [[ "${ERROR_CODE}" -eq "255" && "${STDERR}" =~ "No changes to deploy" ]]; then exit 0; fi 
    
    exit ${ERROR_CODE}

**Comment by jolexa** [comment]
Same here. If the call was a no-op, I just do `|| exit 0` - not ideal but works for my case (shrug)

**Comment by sanathkr** [comment]
Good point. We will get this fixed in the CLI. 

If anyone is interested in sending a PR, here is the relevant code bit: 
Exception is thrown from here: https://github.com/aws/aws-cli/blob/develop/awscli/customizations/cloudformation/deployer.py#L135
Catch ChangeEmptyError Exception here and return a 0 status: https://github.com/aws/aws-cli/blob/develop/awscli/customizations/cloudformation/deploy.py#L164
And, write tests :-)

**Comment by jolexa** [comment]
I was _just_ prepping to fix this and I see that @stan3 has an open PR https://github.com/aws/aws-cli/pull/2606 👍  🎆  Thanks Tristan!

**Comment by sanathkr** [comment]
Closing this in favor of aws cli PR

**Comment by sourceindex** [comment]
Still an issue in version 1.15.26 

### Version Details
```
aws --version
aws-cli/1.15.26 Python/2.7.13 Linux/4.14.33-51.37.amzn1.x86_64 botocore/1.10.26
```

### System Details
```
Debian GNU/Linux 9.4 (stretch) Release:       9.4 Codename:   stretch
Linux f2f521fcf707 4.14.33-51.37.amzn1.x86_64 #1 SMP Thu May 3 20:07:43 UTC 2018 x86_64 GNU/Linux
```

**Comment by bmg-will** [comment]
I have run into this issue with my CI pipeline as well, below is the output from my npm run. 

I have fixed it for now by appending ' || true' to the end of my 'npm run' script, but this will hide legitimate errors when they happen 🙁

`
Waiting for changeset to be created..
No changes to deploy. Stack Api is up to date
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! api@1.0.0 stack-deploy-api: `aws cloudformation deploy --template-file ./Config/aws/cf_stack_api.yaml --stack-name Api --capabilities CAPABILITY_IAM --region eu-west-2`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the api@1.0.0 stack-deploy-api script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-18T09_32_19_052Z-debug.log
`

**Comment by latheesan-k** [comment]
If you are using a bash script to automate the package & deploy then you can add this after the `sam deploy ...` command:

```
if [ "$?" -eq 255 ]
then
    echo "No changes to deploy."
    true
fi

**Comment by rickyinnz** [comment]
Adding `--no-fail-on-empty-changeset` seems to work i.e., allow bash script execution to continue even if there were no updates made to the stack. 

```
aws cloudformation deploy --template-file cloud-formation.yml \
--stack-name xxx \
--no-fail-on-empty-changeset
```

**Comment by bethesque** [comment]
@sanathkr I am confused as to why this is closed in favour of the aws cli change. How does this help those using sam deploy?

@latheesan-k  do you have evidence that the 255 exit status is *only* used when there are no changes to deploy, and for no other reason?

**Comment by mvanbaak** [comment]
> @sanathkr I am confused as to why this is closed in favour of the aws cli change. How does this help those using sam deploy?

Because ```sam deploy``` uses ```aws cloudformation deploy``` in the background

**Comment by latheesan-k** [comment]
@bethesque From what I observed, when you run sam deploy, it always returned 255 with the message about no changes to apply, but I think this is misleading. 

the whole process is deferred, when you deploy it packages up the CF template and uploads it to S3 and then another process kicks in to apply the changes, which can independently fail for various reasons.

**Comment by bethesque** [comment]
@mvanbaak does sam deploy now expose that flag? I tried using the flag with the same name for sam deply, and it failed saying it didn't know what the option was, but I am suspecting my version of the awscli is out of date.

**Comment by mvanbaak** [comment]
@bethesque Yes, then your aws cli is out of date.
```sam deploy``` is just an alias/wrapper around ```aws cloudformation deploy``` and as the help from ```sam deploy --help``` states, you can use all the flags that ```aws cloudformation deploy``` understands. 

I just tested the flag with the latest awscli installed and it works perfectly.

After you updated your awscli, things should work. Good luck!

**Comment by bethesque** [comment]
Thanks @mvanbaak!

**Comment by davethomas11** [comment]
Adding --no-fail-on-empty-changeset works with sam deploy as well
`sam deploy --no-fail-on-empty-changeset --template-file packaged.yaml --stack-name Stack-Name`

**Comment by Jun-depo** [comment]
> Adding `--no-fail-on-empty-changeset` seems to work i.e., allow bash script execution to continue even if there were no updates made to the stack.
> 
> ```
> aws cloudformation deploy --template-file cloud-formation.yml \
> --stack-name xxx \
> --no-fail-on-empty-changeset
> ```

didn't work for me.
