### ISSUE TITLE
AutoPublishAlias not working in cloudformation 

### ISSUE THREAD

**Issue by Private-SO** [awslabs/serverless-application-model#876]
This is an issue. 

**Steps to Reproduce** 

Below are the lambda functions.

**markleV1**
```
exports.handler = async (event) => {
    // TODO implement
    const response = {
        statusCode: 200,
        body: JSON.stringify('Hello from Hades!'),
    };
    return response;
};
```

**markleV2**
```
exports.handler = async (event) => {
    // TODO implement
    const response = {
        statusCode: 200,
        body: JSON.stringify('Hello from Zeus!'),
    };
    return response;
};
```

1) Deploy the below cloudformation template

```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Transform": "AWS::Serverless-2016-10-31",
  "Description": "AWS CloudFormation sample template that contains a single Lambda function behind an API Gateway",

  "Resources": {

      "MyLambdaFunction": {
        "Type": "AWS::Serverless::Function",
        "Properties": {
    "Handler": "markle.js",
    "Runtime": "nodejs8.10",
    "CodeUri": "s3://my-bucket-name/markleV1.zip",
	"AutoPublishAlias": "live",
    "Description": "Creates thumbnails of uploaded images",
    "MemorySize": 1024,
    "Timeout": 15,
    "Policies": [
        "AWSLambdaExecute"
    ]
 }
}
},

  "Outputs": {
    "Version": {
      "Description": "Version ARN",
      "Value": { "Ref" : "MyLambdaFunction.Version" }
    }
  }
}
```
After deploying the above template i can see that it had produced an alias,version and lambda function.

2) Here i had changed the `codeuri` of the above template to like this 
`"CodeUri": "s3://dynamodbputtest/markleV2.zip"`  and updated the stack. As said in the documentation since there is an change in the `codeuri`  it need to publish a new version and assign alias to the new version. But i didnt see any new version .

Am i missing anything?
Any help is appreicated
Thanks

**Comment by keetonian** [comment]
Did your stack update complete successfully?

I just created a stack with `AutoPublishAlias: live` and verified that the alias was created correctly and pointed to the published version of the function. I then updated my function and deployed to the stack again, which caused a new version to be created and the `live` alias was successfully updated to point to that new version.

I could see which version my alias was pointing at by going to the lambda function in the console, clicking "Qualifiers", and verifying that the alias pointed at the latest version (for me, version 2 of my function).

**Comment by Private-SO** [comment]
Thanks @keetonian .

Yeah my stack updated successfully but didnt created new version. You are saying i` had updated the function and deployed to the stack` , Did you tried with my above configuration ?

Because the above configuration didnt worked for me .
Thanks

**Comment by keetonian** [comment]
Ok, I'll try the exact steps you recorded. Did you update the stack with `aws cloudformation deploy` or how did you update the stack?

**Comment by Private-SO** [comment]
No i didn't tried it with `aws cloudformation deploy` , i deployed using cloudformation console.

**Comment by tempo4964** [comment]
I believe AutoPublishAlias is a SAM feature instead of it's cloudformation superset.
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/automating-updates-to-serverless-apps.html

I have my project function configure as below, which is perfectly fine, just fyr.
    ProfilePostFunction:
      Type: "AWS::Serverless::Function"
      Properties:
        Handler: index.handler
        Runtime: nodejs8.10
        FunctionName: !Join ["", [ !Ref EnvrType ,"-", "SI-post-profile-image" ] ]
        Role: 'arn:aws:iam::45645654645645:role/aiportal-lambda-execution-role'
        CodeUri: lambdas/SI-post-profile-image
        AutoPublishAlias: dev
        DeploymentPreference:
          Type: AllAtOnce
          Alarms:
            # A list of alarms that you want to monitor
            - !Ref AliasErrorMetricGreaterThanZeroAlarm
            - !Ref LatestVersionErrorMetricGreaterThanZeroAlarm

**Comment by jlhood** [comment]
SAM templates can be deployed via CloudFormation (Console or CLI). Remaining action item for @keetonian is to try to reproduce via the CloudFormation console.

@Private-SO One thing to note, you are using `AutoPublishAlias` without `DeploymentPreference`. Is that intentional? The two are usually used together.

**Comment by Private-SO** [comment]
@jlhood , Yes my usecase don't need `DeploymentPreference`. Thats the reason i skipped that.

**Comment by keetonian** [comment]
@Private-SO I followed the exact steps that you posted in your original post. You are correct in that a new version is not created when following those steps.

The reason for this is that, when you update the stack in the CloudFormation console, the original SAM template is not used; rather, the transformed CloudFormation template is used. This means that SAM does not run and is not able to change the Function Version resource for you so that the stack deploys a new version.

I can recommend two ways to make this work as expected:

1. If you want to use the designer in the console, if you redeploy a template with a Function Version in it, make a change to the Logical Id of the function version resource and make sure to update the Alias and Outputs with this new logical id, as both of those reference the function version in your sample template.
1. Make changes to your original SAM template and redeploy the template to the same stack and it will make these changes to the Function Version resource for you.

**Comment by kangks** [comment]
If I am using nested stack for functions which are in S3, it is quite count productive to have to touch that nested stack.

Is there any way to force the root stack in SAM to reevaluate the nested stack for the function?

**Comment by whereisaaron** [comment]
`AutoPublishAlias` only creates a new version of the Lambda function if the `CodeUri` changes. This means it fails to cover two common use cases:
1. Code has been updated at same `CodeUri`
2. Environment variable values have been updated, but code (and `CodeUri`) is unchanged.

Environment variable changes should also trigger publishing a new version. Plus we can use a dummy environment variable to trigger code updates from the same `CodeUri`, e.g. `CODE_VERSION=1.2.3`.

If you are using SAM, this bug with `AutoPublishAlias` means you basically need to (pointlessly) repackage and upload the code, just to change the environment variables. That defeats AWS's whole stated use case for environment variables.

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/automating-updates-to-serverless-apps.html
> AutoPublishAlias: By adding this property and specifying an alias name, AWS SAM:
> - Detects when new code is being deployed, based on changes to the Lambda function's Amazon S3 URI.
> - Creates and publishes an updated version of that function with the latest code.

**Comment by pkspks** [comment]
I echo @whereisaaron 's thoughts. Our deployments are right now wrong as changing environment variables is not triggering publishing a new version and any subscription/api pointing to the lambda points to the wrong version.

**Comment by jmnarloch** [comment]
Hey, the problem had been addressed in [latest SAM version](https://github.com/awslabs/serverless-application-model/releases/tag/v1.21.0) by allowing to configure the hash of published Lambda version, so that you don't publish it when you code base haven't changed. This still requires you to modify your build step to include logic for computing the hash code.

**Comment by pkspks** [comment]
@jmnarloch, `AutoPublishCodeSha256` deploys a new SAM app version but does not address deploying a new lambda version for the same SAM app version if it's environment variables change.

**Comment by pkspks** [comment]
@jmnarloch , seems like `AutoPublishCodeSha256` is not allowed to refer a cfn parameter for value (Getting an Internal Server Error). This means we can not pass it during deployment but have predetermine it when publishing the SAM app.

So we still have the issue (https://github.com/awslabs/serverless-application-model/issues/876#issuecomment-550550126) where we have things pointing to the wrong version of lambda when environment variables that get values from cfn parameters change.

**Comment by mokele** [comment]
@whereisaaron did you ever get a solution to this allowing just environment variables to be modified and triggering an update to the alias? This is a severe bug imo, going to have to go and route out whether there is an existing bug filed for it outside of this topic, since the original topic is slightly different (and closed). I've tested it out and the PreTraffic deployment hook successfully triggers giving you the opportunity (in the hook) to catch bugs introduced by env variable changes, but if no alias is updated then what's the point

**Comment by mokele** [comment]
The other related bug is here #413  :+1:

**Comment by kybrdbnd** [comment]
> Hey, the problem had been addressed in [latest SAM version](https://github.com/awslabs/serverless-application-model/releases/tag/v1.21.0) by allowing to configure the hash of published Lambda version through `AutoPublishCodeSha256`. So that you don't the version unless your code base has actually changed. This still requires you to modify your build step to include logic for computing the hash code.

There is a bug, as mentioned in here -> https://github.com/aws/serverless-application-model/issues/1497, I am facing the same issue
